# Generated by Django 5.2 on 2025-11-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_uploadedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
